baseURL = "https://sharedmemory.netlify.com/"
languageCode = "en-us"
title = "Sharedmemory"
theme = "hugo-theme-learn"
defaultContentLanguage = "en"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/braunbearded/sharedmemory/edit/master/content/"
  author = "braunbearded"
  description = "Posts about tech related stuff like programming, hacking, hardware and some personal opinions from time to time"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "bluedark"
  disableSearch = false
  disableLanguageSwitchingButton = false
  disableAssetsBusting = true
  disableInlineCopyToClipBoard = false

[Languages]
[Languages.en]
title = "Sharedmemory"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/braunbearded/sharedmemory"
weight = 10

